### ISSUE TITLE
coinos name/brand to change throughout site

### ISSUE THREAD

**Issue by EngageStrategies** [coinos/coinos-ui-v2#4]
Adam has asked to change the coinos to all lowercase so the name is pronounced as all one word.

![logo black transparent bkg](https://user-images.githubusercontent.com/111467499/188697155-74d8fc71-93d4-4cad-8279-7f661671def7.png)
![white logo transparent bkg](https://user-images.githubusercontent.com/111467499/188697210-5fe6cd35-ae83-41d8-ae9f-78eeb4b237b5.png)

**Comment by secondl1ght** [comment]
Complete
