### ISSUE TITLE
Client Profile QR Code not working with new accounts

### ISSUE THREAD

**Issue by EngageStrategies** [coinos/coinos-ui-v2#6]
I set up my Engage Strategies account and when I go to my profile my EngageStrategy profile it shows  the EngageStrategy@coinos.io qr code.  

The qr code is suppose to scan to be able to pay my EngageStrategy account (like the Wave Coffee qr code you have printed off) but the qr code is not attached to anything.

I have added screenshots here

![Screenshot_20220909-113834_Samsung Internet](https://user-images.githubusercontent.com/111467499/189496015-17269d5e-286c-435a-83c2-6875495ca1f8.jpg)
![Screenshot_20220909-115328_Samsung Internet](https://user-images.githubusercontent.com/111467499/189496018-673ed52e-72b3-4145-b11d-6190b65d5136.jpg)

**Comment by secondl1ght** [comment]
@asoltys I think we want the QR code to contain the lightning address correct?
