### ISSUE TITLE
When entering Payment within my ES account QR code not working with coinos wallet

### ISSUE THREAD

**Issue by EngageStrategies** [coinos/coinos-ui-v2#7]
I log in and go to keypad to enter CAD amount- $1 

It then brings me to 'Add a tip?'  I add 10%

- The 'Apply' button does not work.  Once you hit the % you want, the total at the bottom automatically changes.

When I go to scan the QR code produced, coinos wallet does not read it at all.

I did try using my other coinos wallet too, with the same results

Shakepay and Crypto.com recognize the QR code but are not lightning enabled.

![Apply tip button not working](https://user-images.githubusercontent.com/111467499/189496728-bb23a229-2b1f-440a-8dda-c703f382865e.jpg)
![Total to pay](https://user-images.githubusercontent.com/111467499/189496742-5133f279-c4e2-46a9-bfc7-4081ca10216d.jpg)
![Trying to pay with coinos wallet](https://user-images.githubusercontent.com/111467499/189496744-cbe5aec5-b66c-4dea-8000-295e97472cf1.jpg)
![Enlarge QR code and coinos wallet still not picking it up](https://user-images.githubusercontent.com/111467499/189496750-290c970a-8cd4-404e-82b1-230273b9bea3.jpg)

**Comment by secondl1ght** [comment]
@asoltys this is just because the staging site is still using REGTEST right? The QR code should work in prod.
