### ISSUE TITLE
Clarification on being able to pay with Bitcoin using Lightning wallets

### ISSUE THREAD

**Issue by EngageStrategies** [coinos/coinos-ui-v2#8]
When I go to pay with my non lightning wallet, the address is not recognized. I understand because I  am working on this.

I do not think it is clear on the website or within the Business  that only lightning wallets can be used.

In the business profile QR where is says 'Scan to pay with bitcoin' that you actually need a Bitcoin Lightning wallet.

I see the lightning bolt within the qr code but I am thinking the wording needs to be more clear

Scan to pay with Bitcoin Lightning wallet   

or 

Scan to pay with Bitcoin using your lightning wallet

I will have to update the marketing materials too so it is apparent that only lightning wallets can transact.

**Comment by secondl1ght** [comment]
What do you think @asoltys?

**Comment by asoltys** [comment]
Yeah let's not clutter the invoice page with wording at first but after 20s if they haven't paid we can fade in a "Are you having trouble?" message

**Comment by asoltys** [comment]
The prompt should link to a page that explains that we only accept lightning payments but users can get their own coinos account and fund with an on-chain deposit. Once it confirms they can try paying the merchant from their coinos wallet instead of their external on-chain bitcoin wallet.

**Comment by asoltys** [comment]
The troubleshooting page can have an FAQ that explains other common payment issues like lightning routing failure
